project_identifier: sponge-docs
api_key_env: CROWDIN_API_KEY

files:
  - source: '/locale-src/en/LC_MESSAGES/**/*.po'
    translation: '/locale/%locale_with_underscore%/LC_MESSAGES/**/%original_file_name%'
